# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeRCT(object):
    def setupUi(self, HomeRCT):
        HomeRCT.setObjectName("HomeRCT")
        HomeRCT.resize(640, 311)
        HomeRCT.setStyleSheet("background-image: url(:/recote_RCT/img/backgr2.jpg);")
        self.centralwidget = QtWidgets.QWidget(HomeRCT)
        self.centralwidget.setObjectName("centralwidget")
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(-20, 0, 131, 41))
        self.version.setStyleSheet("image: url(:/recote_RCT/img/version 1.0.png);")
        self.version.setText("")
        self.version.setObjectName("version")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 260, 21, 31))
        self.label_2.setStyleSheet("image: url(:/recote_RCT/img/paper-plane.png);\n"
"    background: transparent;\n"
"    border: none;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.contact = QtWidgets.QLabel(self.centralwidget)
        self.contact.setGeometry(QtCore.QRect(40, 270, 151, 16))
        self.contact.setObjectName("contact")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 100, 371, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 110, 211, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 96, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 20, 81, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.download_tele = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_tele.sizePolicy().hasHeightForWidth())
        self.download_tele.setSizePolicy(sizePolicy)
        self.download_tele.setStyleSheet("image: url(:/recote_RCT/img/download.png);\n"
"    background: transparent;\n"
"    border: none;")
        self.download_tele.setText("")
        self.download_tele.setObjectName("download_tele")
        self.verticalLayout_3.addWidget(self.download_tele)
        self.document_use = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.document_use.sizePolicy().hasHeightForWidth())
        self.document_use.setSizePolicy(sizePolicy)
        self.document_use.setStyleSheet("image: url(:/recote_RCT/img/document.png);\n"
"    background: transparent;\n"
"    border: none;")
        self.document_use.setText("")
        self.document_use.setObjectName("document_use")
        self.verticalLayout_3.addWidget(self.document_use)
        self.document_setupbot = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.document_setupbot.sizePolicy().hasHeightForWidth())
        self.document_setupbot.setSizePolicy(sizePolicy)
        self.document_setupbot.setStyleSheet("image: url(:/recote_RCT/img/document.png);\n"
"    background: transparent;\n"
"    border: none;")
        self.document_setupbot.setText("")
        self.document_setupbot.setObjectName("document_setupbot")
        self.verticalLayout_3.addWidget(self.document_setupbot)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 101, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.setting = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting.sizePolicy().hasHeightForWidth())
        self.setting.setSizePolicy(sizePolicy)
        self.setting.setStyleSheet("image: url(:/recote_RCT/img/settings-sliders.png);\n"
"    background: transparent;\n"
"    border: none;")
        self.setting.setText("")
        self.setting.setObjectName("setting")
        self.horizontalLayout_3.addWidget(self.setting)
        self.home = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home.sizePolicy().hasHeightForWidth())
        self.home.setSizePolicy(sizePolicy)
        self.home.setStyleSheet("image: url(:/recote_RCT/img/home.png);\n"
"background-color: rgb(218, 206, 255);")
        self.home.setText("")
        self.home.setObjectName("home")
        self.horizontalLayout_3.addWidget(self.home)
        HomeRCT.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HomeRCT)
        self.statusbar.setObjectName("statusbar")
        HomeRCT.setStatusBar(self.statusbar)

        self.retranslateUi(HomeRCT)
        QtCore.QMetaObject.connectSlotsByName(HomeRCT)

    def retranslateUi(self, HomeRCT):
        _translate = QtCore.QCoreApplication.translate
        HomeRCT.setWindowTitle(_translate("HomeRCT", "MainWindow"))
        self.contact.setText(_translate("HomeRCT", "daolequocanh2010@gmail.com"))
        self.groupBox.setTitle(_translate("HomeRCT", "Introduction"))
        self.textEdit.setHtml(_translate("HomeRCT", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">bài giới thiệu ....</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">......</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">.....</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">....</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">...</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">...</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">..</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">..</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_2.setTitle(_translate("HomeRCT", "Setup"))
        self.label.setText(_translate("HomeRCT", "Telegram"))
        self.label_3.setText(_translate("HomeRCT", "How to use?"))
        self.label_4.setText(_translate("HomeRCT", "How Setup Bot"))
import rct_ui_rc
